container_config: &container_config
  docker:
    - image: google/cloud-sdk
  environment:
    PROJECT_NAME: orangesys
    CLOUDSDK_COMPUTE_ZONE: asia-northeast1-c
    ORG_PATH: "github.com/orangesys"
    REPO_PATH: "${ORG_PATH}/${CIRCLE_PROJECT_REPONAME}"
install_docker_client: &install_docker_client
  run:
    name: Install docker client
    command: |
      VER="18.06.3-ce"
      curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/edge/x86_64/docker-${VER}.tgz
      tar -xz -C /tmp/ -f /tmp/docker-$VER.tgz
      mv /tmp/docker/* /usr/bin      
workspace_root: &workspace_root
  /tmp/workspace

attach_workspace: &attach_workspace
  attach_workspace:
    at: *workspace_root

version: 2
jobs:
  build_container:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker
      - *install_docker_client
      - run:
          name: Build container images
          command: |
            .circleci/create-container.sh
      - run:
          name: Test influxdb container images
          command: |
            .circleci/checkinfluxdb.sh
      - run:
          name: save container image to workspace
          command: |
            version=$(git describe --always --tags)
            mkdir -p /tmp/workspace
            docker save -o /tmp/workspace/${CIRCLE_PROJECT_REPONAME}.tar "orangesys/${CIRCLE_PROJECT_REPONAME}:${version}"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  deploy:
    <<: *container_config
    steps:
      - *attach_workspace
      - setup_remote_docker
      - *install_docker_client
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /tmp/workspace/${CIRCLE_PROJECT_REPONAME}.tar | true
            docker images
      - run:
          name: Show docker images & set tag & push docker hub and gcloud
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push orangesys/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
            curl -X POST https://hooks.microbadger.com/images/orangesys/alpine-orangesys-influxdb/MxMCnhHfqsOnIeY8lsp535xrNYQ=

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_container:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(.*)*/ 
      - deploy:
          requires:
            - build_container
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(.*)*/
            branches:
              ignore: /.*/
